name: Feature CI/CD Development

on:
  push:
    branches:
      - '*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Test
        run: echo "running on feature branch"

      - name: Deploy
        run: echo "deploying on feature branch"                      
