name: Staging CI/CD Development

on:
  push:
    branches:
      - 'staging/*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Test
        run: echo "running on staging branch"

      - name: Deploy
        run: echo "deploying on staging branch"                      
